/**
 * Classes generated by the Android Studio master-detail activity wizard, and then modified for
 * the Northwind application.
 *
 * @see com.christianschneider.masterdetaildemo.MasterDetailDemo
 */
package com.christianschneider.view;